In [32]:
from sklearn.datasets import fetch_openml 

mnist = fetch_openml('mnist_784', version=1)
mnist.keys()

/Users/damianotto/miniconda3/envs/mllab/lib/python3.9/site-packages/sklearn/datasets/_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [33]:
mnist['DESCR']

"**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  \n**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  \n**Please cite**:  \n\nThe MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  \n\nIt is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 

In [34]:
mnist['data']

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69995       0.0       0.0       0.0       0.0       0.0  
69996       0.0       0.0       0.0       0.0       0.0  
69997       0.0       0.0       0.0       0.0       0.0  
69998       0.0       0.0       0.0       0.0       0.0  
69999       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [35]:
mnist['target']

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [36]:
import numpy as np
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [37]:
X = mnist['data']
y = mnist['target']

y_sorted = y.sort_values()
print(y_sorted.index)

X_sorted = X.reindex(y.index)
print(X_sorted.index)

X_train_form_sorted, X_test_from_sorted = X[:56000], X[56000:]
y_train_from_sorted, y_test_sorted = y[:56000], y[56000:]
print(X_train_form_sorted.shape, y_train_from_sorted.shape)
print(X_test_from_sorted.shape, y_test_sorted.shape)

Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388, 56429,
       ...
       13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678, 58529],
      dtype='int64', length=70000)
RangeIndex(start=0, stop=70000, step=1)
(56000, 784) (56000,)
(14000, 784) (14000,)


In [38]:
print(f'y_train: {y_train_from_sorted.unique()}')
print(f'y_test: {y_test_sorted.unique()}')

y_train: ['5', '0', '4', '1', '9', '2', '3', '6', '7', '8']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']
y_test: ['1', '8', '5', '9', '0', '3', '2', '4', '6', '7']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']


In [43]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(f'y_train: {y_train.unique()}')
print(f'y_test: {y_test.unique()}')

y_train: ['2', '5', '7', '4', '8', '3', '1', '9', '6', '0']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']
y_test: ['2', '1', '8', '7', '4', '0', '5', '6', '3', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']


In [48]:
from sklearn.linear_model import SGDClassifier
import pickle

# Rozpoznawanie zera
y_train_0 = (y_train == '0')
y_test_0 = (y_test == '0')

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)

y_train_0_pred = sgd_clf.predict(X_train)
y_test_0_pred = sgd_clf.predict(X_test)

acc_train = sum(y_train_0_pred == y_train_0) / len(y_train_0)
acc_test = sum(y_test_0_pred == y_test_0) / len(y_test_0)

print(f'Accuracy train: {acc_train}')
print(f'Accuracy test: {acc_test}')

float_list_of_acc = [acc_train, acc_test]

with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump(float_list_of_acc, f)


Accuracy train: 0.9897857142857143
Accuracy test: 0.9873571428571428


In [49]:
from sklearn.model_selection import cross_val_score

cross_value = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring='accuracy')
cross_value = np.array(cross_value)

with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(cross_value, f)

In [51]:
# klasyfikacja dla wszystkich cyfr
from sklearn.metrics import confusion_matrix

sgd_clf.fit(X_train, y_train)

y_train_pred = sgd_clf.predict(X_train)
y_test_pred = sgd_clf.predict(X_test)


In [56]:
confusion_matrix_train = confusion_matrix(y_train, y_train_pred)
confusion_matrix_train = np.array(confusion_matrix_train)

with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(confusion_matrix_train, f)